project:
  type: book
  output-dir: docs
execute:
  freeze: auto  # re-render only when source changes
book:
  title: "mrgsolve cookbook"
  favicon: images/MRG-Solve-Hex.png
  author: "Kyle Baron"
  date: "today"
  date-format: long
  chapters:
    - index.qmd
    - part: "mrgx plugin"
      chapters: 
        - mrgx-assign.qmd
        - mrgx-get.qmd
        - mrgx-rds.qmd
    - part: evtools
      chapters:
        - evtools-0.qmd
        - evtools-1.qmd
    - part: Debugging
      chapters:
        - mrg-report.qmd    
bibliography: references.bib

format:
  html:
    theme: cosmo
    linkcolor: "#097f5f"
  # pdf:
  #   documentclass: scrreprt
  #   toc-depth: 2
